version: '3.8'

services:
  # 1. The Database Service
  db:
    image: postgres:15
    container_name: weather_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432" # Maps the container port to your local machine so you can inspect it later
    volumes:
      - pgdata:/var/lib/postgresql/data # Ensures data isn't lost if the container stops

  # 2. The New Airflow Orchestrator
  airflow:
    image: apache/airflow:2.7.1-python3.9
    container_name: weather_airflow
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False # Don't load the distracting tutorial DAGs
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=weather_db
    ports:
      - "8080:8080" # This exposes the Airflow Web UI to your browser
    volumes:
      - ./dags:/opt/airflow/dags # Maps your local dags folder into the container
    command: standalone # Boots up all Airflow components for local dev

volumes:
  pgdata:
